# -*- coding: utf-8 -*-
import pymysql
import sys

def writeToSQL(dictOfDocumentSet):
    # Try to write the basic file info about the file in SQL.
    # If the file is already in the database, return null to stop the parsing process.

    db = pymysql.connect(
            host    = "localhost"
            ,user   = "root"
            ,passwd = "stufsno1"
            ,db     = "financials"
    )
    cursor_for_SQL  = db.cursor()

    try:
        # Get and return document id automatically generated by SQL
        tableName_in_SQL    = 'DocumentSet'
        temp_Query_holder   = 'SELECT documentSet_id FROM ' + tableName_in_SQL + \
                            ' WHERE edinetCode = %s AND filingDate = %s AND repFileName = %s;'
        values_for_Where    = [
            dictOfDocumentSet['edinetCode']
            ,dictOfDocumentSet['filingDate']
            ,dictOfDocumentSet['repFileName']
        ]
        cursor_for_SQL.execute(temp_Query_holder, values_for_Where)
        DocumentSet_id_in_SQL       = cursor_for_SQL.fetchall()

        # If the document has documentID DocumentSet, return Null and the error code
        if DocumentSet_id_in_SQL:
            return(None, 0)

        # Else if the document is not registered in DocumentSet, insert in DocumentSet and return the newly created id
        else:
            temp_Query_holder = 'INSERT INTO ' + tableName_in_SQL + \
            ' (edinetCode, filingDate, documentType, repFileName) VALUES (%s,%s,%s,%s);'
            values_to_Insert = [
                dictOfDocumentSet['edinetCode']
                ,dictOfDocumentSet['filingDate']
                ,dictOfDocumentSet['documentType']
                ,dictOfDocumentSet['repFileName']
            ]
            cursor_for_SQL.execute(temp_Query_holder, values_to_Insert)

            # Get and return document id automatically generated by SQL
            temp_Query_holder = 'SELECT documentSet_id FROM ' + tableName_in_SQL + \
            ' WHERE edinetCode = %s AND filingDate = %s AND repFileName = %s;'
            values_for_Where = [
                dictOfDocumentSet['edinetCode']
                ,dictOfDocumentSet['filingDate']
                ,dictOfDocumentSet['repFileName']
            ]
            cursor_for_SQL.execute(temp_Query_holder, values_for_Where)
            DocumentSet_id_in_SQL = cursor_for_SQL.fetchall()

            db.commit()
            return(True, DocumentSet_id_in_SQL)

    # if error ocurred, dont read the document
    except:
        db.rollback()
        print(sys.exc_info())
        return(None, 1)

    db.close()
